name: Build and Publish Docker Image

on: [ push ]

env:
  ECR: 617824243747.dkr.ecr.eu-west-1.amazonaws.com
  GHCR: ghcr.io

jobs:
  publish-docker-image:
    name: Publish Docker Image
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check Out
        uses: actions/checkout@v2

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Github Container Registry (GHCR)
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Log in to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.ECR }}/openhim-core:latest
            ${{ env.ECR }}/openhim-core:${{ github.sha }}
            ${{ env.GHCR }}/safesurgerysa/openhim-core:latest
            ${{ env.GHCR }}/safesurgerysa/openhim-core:${{ github.sha }}
