name: Build and Publish Docker Image

on:
  push:
    branches:
      - master

env:
  ECR_PROD: 271399925085.dkr.ecr.eu-west-1.amazonaws.com
  ECR_QA: 617824243747.dkr.ecr.eu-west-1.amazonaws.com
  GHCR: ghcr.io

jobs:
  publish-docker-image:
    name: Publish Docker Image
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check Out
        uses: actions/checkout@v2

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Github Container Registry (GHCR)
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure QA AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.QA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.QA_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Log in to QA AWS ECR
        id: login-qa-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Configure PROD AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Log in to PROD AWS ECR
        id: login-prod-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.ECR_PROD }}/openhim-core:latest
            ${{ env.ECR_PROD }}/openhim-core:${{ github.sha }}
            ${{ env.ECR_QA }}/openhim-core:latest
            ${{ env.ECR_QA }}/openhim-core:${{ github.sha }}
            ${{ env.GHCR }}/safesurgerysa/openhim-core:latest
            ${{ env.GHCR }}/safesurgerysa/openhim-core:${{ github.sha }}
