name: Build and Publish Docker Image

on:
  push:
    branches:
      - master

env:
  ECR_PROD: 271399925085.dkr.ecr.eu-west-1.amazonaws.com
  ECR_PROD_ROLE: arn:aws:iam::271399925085:role/safesurgerysa-prod-pshr-openhim-core-ecr-role
  ECR_QA: 617824243747.dkr.ecr.eu-west-1.amazonaws.com
  ECR_QA_ROLE: arn:aws:iam::617824243747:role/safesurgerysa-qa-pshr-openhim-core-ecr-role
  GHCR: ghcr.io

jobs:
  publish-docker-image:
    name: Publish Docker Image
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Check Out
        uses: actions/checkout@v2

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Github Container Registry (GHCR)
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure QA AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.ECR_QA_ROLE }}
          aws-region: eu-west-1

      - name: Log in to QA AWS ECR
        id: login-qa-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Configure PROD AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.ECR_PROD_ROLE }}
          aws-region: eu-west-1

      - name: Log in to PROD AWS ECR
        id: login-prod-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.ECR_PROD }}/openhim-core:latest
            ${{ env.ECR_PROD }}/openhim-core:${{ github.sha }}
            ${{ env.ECR_QA }}/openhim-core:latest
            ${{ env.ECR_QA }}/openhim-core:${{ github.sha }}
            ${{ env.GHCR }}/safesurgerysa/openhim-core:latest
            ${{ env.GHCR }}/safesurgerysa/openhim-core:${{ github.sha }}
